// ============================================================
// LAPERLA Olive Oil — Données produits pour les pages dédiées
// Source de vérité synchronisée avec public/content.html (PRODUCTS)
// ============================================================

const BASE = {
  origin: 'Haine Zembra la Romaine · Tunisie',
  acidity: '< 0,3 %',
  extraction: 'Première pression à froid · < 27 °C',
  certs: 'ECO-CERT (EU-Bio, TN-BIO-001) · USDA Organic',
};

export const PRODUCTS = [
  {
    id: 'p3',
    slug: 'vestige-250-ml',
    cat: 'glass',
    catLabel: 'Glasflasche',
    ref: 'LP-250-R',
    name: 'Vestige 250 ml',
    vol: '250 ml · Runde Glasflasche',
    notes: 'Kompaktes Format — perfekt zum Probieren oder Mitnehmen.',
    price: 15,
    litres: 0.25,
    img: '/images/img_003.webp',
    images: ['/images/img_003.webp'],
    available: true,
    description:
      'Die kleinste Edition der Vestige-Linie vereint alles, wofür Laperla steht: ein prämiertes, kaltgepresstes Olivenöl extra vergine aus uralten Chemlali-Bäumen Tunesiens. Das kompakte 250-ml-Format ist der elegante Einstieg in die Welt der Édition Prestige — ideal zum Probieren, als stilvolles Mitbringsel oder für die feine Tafel zwischendurch.',
    tasting: [
      'Frische grüne Noten mit Anklängen von grünem Apfel und Artischocke',
      'Feine süße Mandel im Mittelteil, harmonisch ausbalanciert',
      'Seidiger, milder Abgang mit zarter Schärfe im Finale',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Empfehlung', 'Salate, Feinschmecker-Dips, Finishing'],
    ],
  },
  {
    id: 'p2',
    slug: 'vestige-500-ml',
    cat: 'glass',
    catLabel: 'Glasflasche',
    ref: 'LP-500-R',
    name: 'Vestige 500 ml',
    vol: '500 ml · Runde Glasflasche',
    notes: 'Der ideale Einstieg in die Prestige-Linie für die tägliche Tafel.',
    price: 25,
    litres: 0.5,
    img: '/images/img_004.webp',
    images: ['/images/img_004.webp'],
    available: true,
    description:
      'Die Vestige 500 ml ist der ideale Einstieg in die Prestige-Linie von Laperla: großzügig genug für die tägliche Tafel, edel genug für besondere Momente. Jede Flasche enthält prämiertes tunesisches Olivenöl extra vergine — kaltgepresst innerhalb weniger Stunden nach der Ernte, um die volle Frische und die wertvollen Polyphenole zu bewahren.',
    tasting: [
      'Ausdrucksstarke Fruchtigkeit mit grünem Apfel und frischem Gras',
      'Süße Mandel und ein Hauch von grüner Tomate',
      'Eleganter, seidiger Abgang mit feiner, ausgewogener Schärfe',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Empfehlung', 'Tägliche Küche, Salate, Gemüse, Finishing'],
    ],
  },
  {
    id: 'p1',
    slug: 'vestige-750-ml',
    cat: 'glass',
    catLabel: 'Glasflasche',
    ref: 'LP-750-R',
    flag: 'Best in the World · Genf',
    name: 'Vestige 750 ml',
    vol: '750 ml · Runde Glasflasche',
    notes: 'Das Flaggschiff der Édition Prestige. Grüner Apfel, süße Mandel, seidiger Abgang.',
    price: 30,
    litres: 0.75,
    img: '/images/img_005.webp',
    images: ['/images/img_005.webp'],
    available: true,
    description:
      'Die Vestige 750 ml ist das Flaggschiff der Édition Prestige — ausgezeichnet als „Best Olive Oil in the World“ in Genf. Aus den Früchten uralter Chemlali-Bäume entsteht ein Olivenöl extra vergine von seltener Reinheit: kaltgepresst, ungefiltert belassen in seiner natürlichen Eleganz und in eine Flasche gefüllt, die jedem Regal und jeder Tafel Ehre macht.',
    tasting: [
      'Intensiv fruchtige Eröffnung — grüner Apfel, frisch geschnittenes Gras',
      'Süße Mandel und feine Artischocken-Noten im Herzen',
      'Langer, seidiger Abgang mit edler, harmonischer Schärfe',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Auszeichnung', 'Best Olive Oil in the World · Genf'],
      ['Empfehlung', 'Signature-Finishing, Carpaccio, Burrata, Brot'],
    ],
  },
  {
    id: 'p10',
    slug: 'vestige-carre-500-ml',
    cat: 'glass',
    catLabel: 'Glasflasche',
    ref: 'LP-500-C',
    name: 'Vestige Carré 500 ml',
    vol: '500 ml · Eckige Glasflasche',
    notes: 'Die Édition Prestige in der eleganten eckigen Flasche — markant im Regal, edel auf der Tafel.',
    price: 25,
    litres: 0.5,
    img: '/images/img_079.webp',
    images: ['/images/img_079.webp'],
    available: true,
    description:
      'Die Vestige Carré interpretiert die Édition Prestige in einer markanten, eckigen Glasflasche neu: architektonisch klar, modern und unverwechselbar. Im Inneren dasselbe prämierte tunesische Olivenöl extra vergine — kaltgepresst, bio-zertifiziert und voller Frische. Ein Design-Statement für alle, die Ästhetik und Substanz gleichermaßen schätzen.',
    tasting: [
      'Frische, grüne Frucht mit Noten von Apfel und Artischocke',
      'Feine Mandel-Süße, elegant und präzise',
      'Ausgewogener Abgang mit zarter, edler Schärfe',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Besonderheit', 'Eckige Design-Flasche · Carré-Linie'],
    ],
  },
  {
    id: 'p11',
    slug: 'vestige-carre-750-ml',
    cat: 'glass',
    catLabel: 'Glasflasche',
    ref: 'LP-750-C',
    name: 'Vestige Carré 750 ml',
    vol: '750 ml · Eckige Glasflasche',
    notes: 'Das 750-ml-Format in der eckigen Prestige-Flasche — ein Statement für anspruchsvolle Genießer.',
    price: 30,
    litres: 0.75,
    img: '/images/img_080.webp',
    images: ['/images/img_080.webp'],
    available: true,
    description:
      'Das große Format der Carré-Linie: 750 ml prämiertes Olivenöl extra vergine in der eckigen Prestige-Flasche. Die Vestige Carré 750 ml ist ein Statement für anspruchsvolle Genießer — architektonisch im Design, kompromisslos im Inhalt. Kaltgepresst aus handgelesenen Chemlali-Oliven, bio-zertifiziert und mehrfach international ausgezeichnet.',
    tasting: [
      'Kraftvolle grüne Frucht, grüner Apfel und frische Kräuter',
      'Süße Mandel, fein ausbalanciert mit Artischocke',
      'Langer, seidiger Abgang mit präziser, eleganter Schärfe',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Besonderheit', 'Eckige Design-Flasche · Carré-Linie'],
    ],
  },
  {
    id: 'p9',
    slug: 'vestige-1l-magnum',
    cat: 'glass',
    catLabel: 'Glasflasche',
    ref: 'LP-1000-M',
    flag: 'Magnum',
    name: 'Vestige 1 L',
    vol: '1 L · Eckige Glasflasche',
    notes: 'Großzügig, prestigeträchtig — der Klassiker im Magnum-Format.',
    price: 35,
    litres: 1,
    img: '/images/img_078.webp',
    images: ['/images/img_078.webp'],
    available: true,
    description:
      'Die Magnum der Édition Prestige: ein ganzer Liter prämierten tunesischen Olivenöls extra vergine in der imposanten eckigen Glasflasche. Die Vestige 1 L verbindet Großzügigkeit mit Prestige — für Haushalte, die täglich mit Spitzenqualität kochen, und für Tafeln, auf denen die Flasche selbst ein Statement ist.',
    tasting: [
      'Vollmundige grüne Frucht mit Apfel und frischem Gras',
      'Süße Mandel und feine Kräuterwürze im Mittelteil',
      'Harmonischer, langer Abgang mit edler Schärfe',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Besonderheit', 'Magnum-Format · 1 Liter'],
    ],
  },
  {
    id: 'p4',
    slug: 'heritage-kanister-1l',
    cat: 'tin',
    catLabel: 'Metallkanister',
    ref: 'LP-TIN-1L',
    flag: 'Nicht verfügbar',
    name: 'Heritage Kanister 1 L',
    vol: '1 L · Metallkanister',
    notes: 'Lichtdicht versiegelt — schützt Polyphenole über Monate.',
    price: 35,
    litres: 1,
    img: '/images/img_082.webp',
    images: ['/images/img_082.webp'],
    available: false,
    description:
      'Der Heritage Kanister 1 L schützt das prämierte Olivenöl extra vergine lichtdicht und luftdicht versiegelt — so bleiben die wertvollen Polyphenole und die volle Frische über Monate bewahrt. Die Heritage-Linie steht für funktionale Eleganz: robust im Alltag, edel in der Anmutung.',
    tasting: [
      'Frische grüne Noten, klar und präzise',
      'Süße Mandel mit feiner Kräuterwürze',
      'Ausgewogener, seidiger Abgang',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Besonderheit', 'Lichtdichter Metallkanister · optimaler Schutz'],
    ],
  },
  {
    id: 'p5',
    slug: 'heritage-kanister-3l',
    cat: 'tin',
    catLabel: 'Metallkanister',
    ref: 'LP-TIN-3L',
    badge: 'Mehrfach goldprämiert 2026',
    trust: 'Mit internationalen Goldmedaillen ausgezeichnet — ein sichtbares Qualitätsversprechen für anspruchsvolle Käufer.',
    name: 'Heritage Kanister 3 L',
    vol: '3 L · Metallkanister',
    notes: 'Für Genießer und Familien, die Laperla großzügig schätzen.',
    price: 65,
    litres: 3,
    img: '/images/img_081.webp',
    images: ['/images/img_081.webp'],
    available: true,
    description:
      'Der Heritage Kanister 3 L ist die großzügige Vorrats-Edition für Genießer und Familien: drei Liter mehrfach goldprämiertes Olivenöl extra vergine, lichtdicht und aromageschützt im edlen Metallkanister. Die ideale Verbindung aus Spitzenqualität, Vorrat und Wert — jeden Tag aufs Neue frisch dosiert.',
    tasting: [
      'Intensive Frucht mit grünem Apfel und frischen Kräutern',
      'Süße Mandel, fein verwoben mit Artischocke',
      'Langer, eleganter Abgang mit harmonischer Schärfe',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Auszeichnung', 'Mehrfach goldprämiert · 2026'],
      ['Besonderheit', 'Vorrats-Edition · lichtdicht versiegelt'],
    ],
  },
  {
    id: 'p8',
    slug: 'heritage-kanister-5l',
    cat: 'tin',
    catLabel: 'Metallkanister',
    ref: 'LP-TIN-5L',
    badge: 'Mehrfach goldprämiert 2026',
    trust: 'Mit internationalen Goldmedaillen ausgezeichnet — ein sichtbares Qualitätsversprechen für anspruchsvolle Käufer.',
    name: 'Heritage Kanister 5 L',
    vol: '5 L · Metallkanister',
    notes: 'Das Großformat für die anspruchsvolle Küche.',
    price: 99.9,
    litres: 5,
    img: '/images/img_077.webp',
    images: ['/images/img_077.webp'],
    available: true,
    description:
      'Das Großformat für die anspruchsvolle Küche: fünf Liter mehrfach goldprämiertes tunesisches Olivenöl extra vergine im lichtdichten Metallkanister. Der Heritage Kanister 5 L ist die Wahl von Feinköchen, Familien und Gastronomen, die keine Kompromisse eingehen — Spitzenqualität im großzügigen Format, bis zum letzten Tropfen frisch.',
    tasting: [
      'Kraftvolle, frische Frucht — grüner Apfel und Kräuter',
      'Süße Mandel mit eleganter Artischocken-Note',
      'Ausdrucksstarker, langer Abgang mit feiner Schärfe',
    ],
    details: [
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Auszeichnung', 'Mehrfach goldprämiert · 2026'],
      ['Empfehlung', 'Anspruchsvolle Küche, Gastronomie, Vorrat'],
    ],
  },
  {
    id: 'p6',
    slug: 'coffret-prestige',
    cat: 'gift',
    catLabel: 'Geschenkedition',
    ref: 'LP-COF-TRIO',
    flag: 'Wieder verfügbar',
    name: 'Coffret Prestige',
    vol: '3 × 250 ml · Geschenkbox',
    notes: 'Drei 250-ml-Flaschen der Édition Prestige — das elegante Trio-Geschenkset für besondere Anlässe.',
    price: 35,
    litres: 0.75,
    img: '/images/img_003.webp',
    images: ['/images/img_003.webp', '/images/img_003.webp', '/images/img_003.webp'],
    available: true,
    description:
      'Das Coffret Prestige vereint drei 250-ml-Flaschen der Édition Prestige in einer eleganten Geschenkbox — das stilvollste Trio für besondere Anlässe. Ob als Dankeschön, zum Jubiläum oder als exklusives Mitbringsel: Mit diesem Set verschenken Sie dreimal prämierte tunesische Spitzenqualität, würdig inszeniert.',
    tasting: [
      'Frische grüne Frucht mit Apfel und Artischocke',
      'Süße Mandel, harmonisch und fein',
      'Seidiger Abgang mit zarter, edler Schärfe',
    ],
    details: [
      ['Inhalt', '3 × 250 ml · runde Glasflaschen'],
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Anlass', 'Geschenk, Jubiläum, Mitbringsel'],
    ],
  },
  {
    id: 'p7',
    slug: 'coffret-or-supreme',
    cat: 'gift',
    catLabel: 'Geschenkedition',
    ref: 'LP-COF-OR-3',
    flag: 'Édition Or',
    name: 'Coffret Or Suprême',
    vol: '3 × 750 ml · Prestige-Set',
    notes: 'Drei 750-ml-Flaschen der Édition Prestige — das ultimative Geschenk für höchste Ansprüche.',
    price: 90,
    litres: 2.25,
    img: '/images/img_005.webp',
    images: ['/images/img_005.webp', '/images/img_005.webp', '/images/img_005.webp'],
    available: true,
    description:
      'Das Coffret Or Suprême ist das ultimative Geschenk für höchste Ansprüche: drei 750-ml-Flaschen der prämierten Édition Prestige in einer luxuriösen Geschenkbox. Ein Geschenk, das bleibt — für Geschäftspartner, Sammler und alle, die das Außergewöhnliche suchen. Dreifache Spitzenqualität, einmalig in Szene gesetzt.',
    tasting: [
      'Intensiv fruchtig — grüner Apfel, frisches Gras, Kräuter',
      'Süße Mandel und feine Artischocke im Mittelteil',
      'Langer, seidiger Abgang mit edler, präziser Schärfe',
    ],
    details: [
      ['Inhalt', '3 × 750 ml · runde Glasflaschen'],
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Anlass', 'Luxusgeschenk, Geschäftspartner, Sammler'],
    ],
  },
  {
    id: 'pgb',
    slug: 'vestige-500-geschenkbox',
    cat: 'gift',
    catLabel: 'Geschenkedition',
    ref: 'LP-500-GB',
    flag: 'La Pièce Maîtresse',
    hidden: true,
    name: 'Vestige 500 ml · Geschenkbox-Edition',
    vol: '500 ml · Geschenkbox mit Goldprägung',
    notes: 'Das Flaggschiff der Édition Prestige — überreicht in der schwarzen Geschenkbox. Limitierte Charge.',
    price: 50,
    litres: 0.5,
    img: '/images/vestige_premium.webp',
    images: ['/images/vestige_premium.webp'],
    available: true,
    description:
      'La Pièce Maîtresse der Kollektion: die Vestige 500 ml, überreicht in einer schwarzen Geschenkbox mit feiner Goldprägung. Diese limitierte Charge vereint das prämierte Flaggschiff-Öl der Édition Prestige mit einer Verpackung, die jedes Öffnen zum Ritual macht. Für Momente, in denen nur das Beste gut genug ist.',
    tasting: [
      'Ausdrucksstarke grüne Frucht — Apfel, Gras, Kräuter',
      'Süße Mandel, seidig und präzise',
      'Langer, edler Abgang mit harmonischer Schärfe',
    ],
    details: [
      ['Inhalt', '500 ml · runde Glasflasche in Geschenkbox'],
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Besonderheit', 'Limitierte Charge · Goldprägung'],
    ],
  },
  {
    id: 'p4x5',
    slug: 'coffret-kanister-maison',
    cat: 'gift',
    catLabel: 'Geschenkedition',
    ref: 'LP-KAN-4X5',
    flag: 'Maison Edition',
    name: 'Coffret Kanister Maison',
    vol: '4 × 5 L · Großformat-Set',
    notes: 'Vier 5-Liter-Metallkanister der Édition Prestige — für die ambitionierte Küche und exklusive Gastgeschenke.',
    price: 350,
    litres: 20,
    img: '/images/img_077.webp',
    images: ['/images/img_077.webp', '/images/img_077.webp', '/images/img_077.webp', '/images/img_077.webp'],
    available: true,
    description:
      'Die Maison Edition für das ganze Haus: vier 5-Liter-Metallkanister der Édition Prestige im exklusiven Großformat-Set. Zwanzig Liter prämiertes tunesisches Olivenöl extra vergine — für ambitionierte Küchen, Weitergabe an Gäste und alle, die Vorräte in Spitzenqualität schätzen. Großzügig gedacht, edel gemacht.',
    tasting: [
      'Frische, kraftvolle Frucht mit grünem Apfel',
      'Süße Mandel und feine Kräuterwürze',
      'Langer, eleganter Abgang mit feiner Schärfe',
    ],
    details: [
      ['Inhalt', '4 × 5 L · Metallkanister'],
      ['Herkunft', BASE.origin],
      ['Olivensorte', 'Chemlali · handgelesen'],
      ['Säuregehalt', BASE.acidity],
      ['Extraktion', BASE.extraction],
      ['Zertifizierungen', BASE.certs],
      ['Empfehlung', 'Ambitionierte Küche, Gastgeschenke, Vorrat'],
    ],
  },
];

export const MEDALS = [
  { y: 'Al Ain 2026', l: 'Gold' },
  { y: 'Genf 2026', l: 'Gold' },
  { y: 'Bari 2026', l: 'Gold' },
  { y: 'Genf 2024', l: 'Best in World' },
  { y: 'Miami 2024', l: 'Gold' },
  { y: 'Abu Dhabi 2024', l: 'Gold' },
  { y: 'Bari 2024', l: 'Extragold' },
  { y: 'Athen 2023', l: 'Double Gold' },
];

export function getProductBySlug(slug) {
  return PRODUCTS.find((p) => p.slug === slug) || null;
}

export function getRelatedProducts(product, count = 3) {
  const sameCat = PRODUCTS.filter((p) => p.id !== product.id && !p.hidden && p.cat === product.cat);
  const others = PRODUCTS.filter((p) => p.id !== product.id && !p.hidden && p.cat !== product.cat);
  return [...sameCat, ...others].slice(0, count);
}

export function fmtPrice(n) {
  return n.toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + ' €';
}

export function perLitre(p) {
  if (!p.litres) return '';
  return (p.price / p.litres).toLocaleString('de-DE', { minimumFractionDigits: 2, maximumFractionDigits: 2 }) + ' €/L';
}
